function stations = importAirfile(filename, dataLines)
%IMPORTFILE7 Import data from a text file
%  STATIONS = IMPORTFILE7(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  STATIONS = IMPORTFILE7(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  stations = importfile7("C:\Users\lsammon\OneDrive - MathWorks\Documents\MATLAB\4_Seminars\NOAA boulder2026\Madrid_Air_Quality-main\stations.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 17-Jun-2026 10:04:16

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["id", "name", "address", "lon", "lat", "elevation"];
opts.VariableTypes = ["double", "string", "string", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["name", "address"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["name", "address"], "EmptyFieldRule", "auto");

% Import the data
stations = readtable(filename, opts);

end